# Tutorial 3 - Python For Data Analysis 🐍 

---

## Pandas

### *Table of Contents*

- Pandas 🐼
  - [Introduction](#intro)
  - [Exercice 1](#exercise-5) : Explore Pandas DataFrame basic functions
  - [Exercise 2](#exercise-6) : Explore traffic accidents vehicles

In [2]:
import pandas as pd
import numpy as np

## Pandas 🐼

<a name="intro">

### Introduction - Traffic Accidents Database
---

https://www.data.gouv.fr/fr/datasets/base-de-donnees-accidents-corporels-de-la-circulation/

For each personal injury accident, information describing the accident is entered by the law enforcement unit that intervened at the scene of the accident. These seizures are brought together in a sheet called the personal accident analysis report. All of these files constitute the national file of traffic accidents known as the "BAAC File" administered by the National Intermenstrual Road Safety Observatory "ONISR".

The databases, extracted from the BAAC file, list all of the bodily injury accidents occurring during a specific year in mainland France, in the overseas departments (Guadeloupe, Guyana, Martinique, Réunion and Mayotte since 2012) and in the other overseas territories (Saint-Pierre- et-Miquelon, Saint-Barthélemy, Saint-Martin, Wallis-et-Futuna, French Polynesia and New Caledonia; available only from 2019 in open data) with a simplified description. This includes accident location information, as entered as well as information regarding the characteristics of the accident and its location, the vehicles involved and their victims.

The databases from 2005 to 2019 are now annual and made up of 4 files (Characteristics - Locations - Vehicles - Users) in csv format.

Links to databases:
- https://www.data.gouv.fr/fr/datasets/r/be2191a6-a7cd-446f-a9fc-8d698688eb9e 
- https://www.data.gouv.fr/fr/datasets/r/e4c6f4fe-7c68-4a1d-9bb6-b0f1f5d45526 
- https://www.data.gouv.fr/fr/datasets/r/08b77510-39c4-4761-bf02-19457264790f 
- https://www.data.gouv.fr/fr/datasets/r/96aadc9f-0b55-4e9a-a70e-c627ed97e6f7
   
SETUP : We’ll use vehicles database. 

Import the data using pandas library.`pd.read_csv(url)`

In [3]:
df = pd.read_csv("vehicules_2016.csv")
df.head()

Num_Acc  senc  catv  occutc  obs  obsm  choc  manv num_veh
0  201600000001   0.0     7       0  0.0   0.0   1.0   1.0     B02
1  201600000001   0.0     2       0  0.0   0.0   7.0  15.0     A01
2  201600000002   0.0     7       0  6.0   0.0   1.0   1.0     A01
3  201600000003   0.0     7       0  0.0   1.0   6.0   1.0     A01
4  201600000004   0.0    32       0  0.0   0.0   1.0   1.0     B02

<a name="exercise-5">

### Exercise 1 : Explore Pandas DataFrame basic functions
---

1) How many columns do we have in the DataFrame ? How many rows do we have ?

In [4]:
df.shape

(101924, 9)

2) What are the types of columns in the DataFrame ? Use `info()` function.

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101924 entries, 0 to 101923
Data columns (total 9 columns):
 #   Column   Non-Null Count   Dtype  
---  ------   --------------   -----  
 0   Num_Acc  101924 non-null  int64  
 1   senc     101852 non-null  float64
 2   catv     101924 non-null  int64  
 3   occutc   101924 non-null  int64  
 4   obs      101886 non-null  float64
 5   obsm     101874 non-null  float64
 6   choc     101913 non-null  float64
 7   manv     101917 non-null  float64
 8   num_veh  101924 non-null  object 
dtypes: float64(5), int64(3), object(1)
memory usage: 7.0+ MB


3) Calculate the mean of numeric columns.

In [15]:
#df.select_dtypes(include='number').mean()
df.select_dtypes(include=np.number).mean()

Num_Acc    2.016000e+11
senc       1.041433e+00
catv       1.204036e+01
occutc     7.061144e-02
obs        8.706299e-01
obsm       1.594941e+00
choc       2.857947e+00
manv       5.703896e+00
dtype: float64

4) Calculate the maximum and minimum value of numeric column.

In [17]:
df.select_dtypes(include=np.number).min()

Num_Acc    2.016000e+11
senc       0.000000e+00
catv       1.000000e+00
occutc     0.000000e+00
obs        0.000000e+00
obsm       0.000000e+00
choc       0.000000e+00
manv       0.000000e+00
dtype: float64

In [18]:
df.select_dtypes(include=np.number).max()

Num_Acc    2.016001e+11
senc       2.000000e+00
catv       9.900000e+01
occutc     3.000000e+02
obs        1.600000e+01
obsm       9.000000e+00
choc       9.000000e+00
manv       2.400000e+01
dtype: float64

5) Use `describe()` function, what can you observe ?

Answer : We observe a generate descriptive statistics.

Descriptive statistics include those that summarize the central tendency, dispersion and shape of a dataset’s distribution, excluding NaN values.

In [19]:
df.describe()

Num_Acc           senc           catv         occutc  \
count  1.019240e+05  101852.000000  101924.000000  101924.000000   
mean   2.016000e+11       1.041433      12.040363       0.070611   
std    1.711804e+04       0.747403      11.028127       2.221603   
min    2.016000e+11       0.000000       1.000000       0.000000   
25%    2.016000e+11       0.000000       7.000000       0.000000   
50%    2.016000e+11       1.000000       7.000000       0.000000   
75%    2.016000e+11       2.000000      10.000000       0.000000   
max    2.016001e+11       2.000000      99.000000     300.000000   

                 obs           obsm           choc           manv  
count  101886.000000  101874.000000  101913.000000  101917.000000  
mean        0.870630       1.594941       2.857947       5.703896  
std         2.931908       1.145935       2.476565       7.042847  
min         0.000000       0.000000       0.000000       0.000000  
25%         0.000000       1.000000       1.000000       1.000000  
50%         0.000000       2.000000       2.000000       1.000000  
75%         0.000000       2.000000       4.000000      13.000000  
max        16.000000       9.000000       9.000000      24.000000

6) Display the first 30 values, then last 30.

In [20]:
df.head(30)

Num_Acc  senc  catv  occutc   obs  obsm  choc  manv num_veh
0   201600000001   0.0     7       0   0.0   0.0   1.0   1.0     B02
1   201600000001   0.0     2       0   0.0   0.0   7.0  15.0     A01
2   201600000002   0.0     7       0   6.0   0.0   1.0   1.0     A01
3   201600000003   0.0     7       0   0.0   1.0   6.0   1.0     A01
4   201600000004   0.0    32       0   0.0   0.0   1.0   1.0     B02
5   201600000004   0.0     7       0   0.0   0.0   8.0  15.0     A01
6   201600000005   0.0    30       0   0.0   2.0   1.0  15.0     B02
7   201600000005   0.0     7       0   0.0   2.0   3.0   1.0     A01
8   201600000006   0.0     7       0   0.0   1.0   1.0   1.0     A01
9   201600000007   1.0    30       0   0.0   0.0   3.0  15.0     A01
10  201600000007   1.0     7       0   0.0   2.0   2.0  17.0     B02
11  201600000008   0.0     7       0   0.0   2.0   2.0   1.0     B02
12  201600000008   0.0     7       0   0.0   2.0   3.0  13.0     A01
13  201600000009   0.0     7       0   0.0   0.0   3.0   1.0     A01
14  201600000009   0.0    30       0   0.0   0.0   2.0   1.0     B02
15  201600000010   0.0     7       0   0.0   1.0   2.0   1.0     A01
16  201600000011   0.0     7       0   0.0   1.0   1.0   1.0     A01
17  201600000012   0.0    33       0   0.0   0.0   0.0   1.0     A01
18  201600000013   0.0     7       0   0.0   1.0   2.0   1.0     A01
19  201600000014   0.0    33       0   0.0   2.0   1.0  13.0     A01
20  201600000014   0.0    33       0  14.0   0.0   9.0  21.0     B02
21  201600000014   0.0     7       0   0.0   2.0   3.0   1.0     C03
22  201600000015   0.0     1       0   0.0   2.0   1.0   0.0     B02
23  201600000015   0.0     1       0   0.0   2.0   1.0   0.0     C03
24  201600000015   0.0     7       0   0.0   2.0   3.0  16.0     A01
25  201600000016   0.0     7       0   0.0   2.0   5.0  10.0     C03
26  201600000016   0.0     7       0   0.0   2.0   2.0  10.0     B02
27  201600000016   0.0    33       0   0.0   2.0   2.0   1.0     A01
28  201600000017   0.0     7       0   2.0   0.0   8.0   1.0     A01
29  201600000018   1.0     7       0   0.0   2.0   1.0   0.0     A01

In [21]:
df.tail(30)

Num_Acc  senc  catv  occutc   obs  obsm  choc  manv num_veh
101894  201600059412   2.0    32       0   0.0   2.0   1.0   1.0     B01
101895  201600059413   1.0    30       0  14.0   0.0   8.0  15.0     A01
101896  201600059414   1.0     7       0   0.0   2.0   8.0   1.0     A01
101897  201600059414   2.0    30       0   0.0   2.0   1.0  15.0     B01
101898  201600059415   2.0    36       0   0.0   1.0   1.0  17.0     A01
101899  201600059416   2.0     7       0   0.0   1.0   3.0   1.0     A01
101900  201600059417   1.0     7       0   0.0   2.0   1.0   1.0     A01
101901  201600059417   2.0     7       0   0.0   0.0   0.0  24.0     Z01
101902  201600059418   2.0     7       0   0.0   1.0   3.0   1.0     A01
101903  201600059419   1.0     7       0   0.0   1.0   0.0   0.0     Z01
101904  201600059420   1.0     7       0   0.0   1.0   2.0   1.0     A01
101905  201600059421   1.0     7       0  16.0   0.0   7.0  14.0     A01
101906  201600059422   1.0     7       0   0.0   2.0   3.0  15.0     A01
101907  201600059422   1.0     1       0   0.0   2.0   1.0   1.0     B01
101908  201600059423   2.0    33       0   0.0   2.0   8.0  14.0     A01
101909  201600059423   2.0    32       0   0.0   2.0   8.0   1.0     B01
101910  201600059424   2.0    32       0   0.0   1.0   1.0   1.0     A01
101911  201600059425   2.0    32       0   0.0   2.0   7.0  17.0     A01
101912  201600059425   1.0     7       0   0.0   2.0   0.0   1.0     Z01
101913  201600059426   2.0     1       0   0.0   2.0   1.0   9.0     A01
101914  201600059426   2.0     7       0   0.0   9.0   7.0   1.0     B01
101915  201600059427   1.0     2       0   0.0   1.0   1.0   1.0     A01
101916  201600059428   2.0    32       0   0.0   1.0   7.0   1.0     A01
101917  201600059429   2.0    30       0  11.0   0.0   1.0  14.0     A01
101918  201600059430   2.0     7       0   0.0   2.0   8.0  15.0     A01
101919  201600059430   1.0    30       0   0.0   2.0   1.0  17.0     B01
101920  201600059431   2.0    30       0   0.0   2.0   7.0  15.0     A01
101921  201600059431   1.0    30       0   0.0   2.0   1.0   1.0     B01
101922  201600059432   1.0     2       0   0.0   2.0   7.0   1.0     A01
101923  201600059432   2.0     7       0   0.0   2.0   1.0   9.0     B01

<a name="exercise-6">

### Exercise 2 : Explore traffic accidents vehicles
---

Read the documentation to understand the meanings of each column.
 
Documentation: https://www.data.gouv.fr/fr/datasets/r/6cade01c-f69d-4779-b0a4-20606069888f

1) Then display the column names and rename it with the names of your choice. For the following questions, we use these column names:
```
[
"Num_Acc", "sens_de_Circulation", "catV", "nb_occupants", "obstacle_fixe", "obstacle_mobile", "choc", "manoeuvre" , "num_vehicule"
]
```

In [22]:
df.columns

Index(['Num_Acc', 'senc', 'catv', 'occutc', 'obs', 'obsm', 'choc', 'manv',
       'num_veh'],
      dtype='object')

In [25]:
columns = ["Num_Acc", "sens_de_Circulation", "catV", "nb_occupants", "obstacle_fixe", "obstacle_mobile", "choc", "manoeuvre" , "num_vehicule"]
df.set_axis(columns, axis='columns', inplace = True)

In [26]:
df.columns

Index(['Num_Acc', 'sens_de_Circulation', 'catV', 'nb_occupants',
       'obstacle_fixe', 'obstacle_mobile', 'choc', 'manoeuvre',
       'num_vehicule'],
      dtype='object')

2) Get the number of null values by column. Then, display its proportion in the DataFrame. 
For example : 0.08% of col_1 are null

In [29]:
df.isnull().sum()

Num_Acc                 0
sens_de_Circulation    72
catV                    0
nb_occupants            0
obstacle_fixe          38
obstacle_mobile        50
choc                   11
manoeuvre               7
num_vehicule            0
dtype: int64

In [30]:
df.isnull().mean() * 100

Num_Acc                0.000000
sens_de_Circulation    0.070641
catV                   0.000000
nb_occupants           0.000000
obstacle_fixe          0.037283
obstacle_mobile        0.049056
choc                   0.010792
manoeuvre              0.006868
num_vehicule           0.000000
dtype: float64

In [31]:
df.isnull().sum() / df.shape[0] * 100.00

Num_Acc                0.000000
sens_de_Circulation    0.070641
catV                   0.000000
nb_occupants           0.000000
obstacle_fixe          0.037283
obstacle_mobile        0.049056
choc                   0.010792
manoeuvre              0.006868
num_vehicule           0.000000
dtype: float64

In [33]:
percent = df.isnull().sum() * 100 / len(df)
missing = pd.DataFrame({'Percentage of missing values': round(percent,2)})
missing

Percentage of missing values
Num_Acc                                      0.00
sens_de_Circulation                          0.07
catV                                         0.00
nb_occupants                                 0.00
obstacle_fixe                                0.04
obstacle_mobile                              0.05
choc                                         0.01
manoeuvre                                    0.01
num_vehicule                                 0.00

#### Exploratory Data Analysis - Filters

3) Select `obstacle fixe` column, what is the type of returned value ?

In [35]:
df['obstacle_fixe'].dtypes

dtype('float64')

In [38]:
type(df['obstacle_fixe'].values[0])

numpy.float64

4) Convert the returned value to a NumPy array

In [39]:
df['obstacle_fixe'].values

array([0., 0., 6., ..., 0., 0., 0.])

In [40]:
type(df['obstacle_fixe'].values)

numpy.ndarray

5) Compute the maximum value of the NumPy array

In [42]:
max(df['obstacle_fixe'].values)

16.0

6) Select `catV` & `sens_de_Circulation columns together

In [43]:
df[['catV','sens_de_Circulation']]

catV  sens_de_Circulation
0          7                  0.0
1          2                  0.0
2          7                  0.0
3          7                  0.0
4         32                  0.0
...      ...                  ...
101919    30                  1.0
101920    30                  2.0
101921    30                  1.0
101922     2                  1.0
101923     7                  2.0

[101924 rows x 2 columns]

7) Select all the columns containing ‘obstacle’ in their name

In [52]:
df.loc[:,df.columns.str.contains('obstacle')]
#df.filter(regex='obstacle',axis=1)
#df[[i for i in df.columns if 'obstacle' in i]]

obstacle_fixe  obstacle_mobile
0                 0.0              0.0
1                 0.0              0.0
2                 6.0              0.0
3                 0.0              1.0
4                 0.0              0.0
...               ...              ...
101919            0.0              2.0
101920            0.0              2.0
101921            0.0              2.0
101922            0.0              2.0
101923            0.0              2.0

[101924 rows x 2 columns]

8) Select all rows with null values for 'sens_de_Circulation' column

In [54]:
df.loc[df['sens_de_Circulation'].isna()]

Num_Acc  sens_de_Circulation  catV  nb_occupants  obstacle_fixe  \
4153   201600002519                  NaN     1             0            0.0   
4504   201600002732                  NaN     7             0            0.0   
8407   201600005135                  NaN     7             0            0.0   
12686  201600007810                  NaN     7             0            0.0   
14845  201600009146                  NaN     1             0            NaN   
...             ...                  ...   ...           ...            ...   
74516  201600044276                  NaN     7             0            0.0   
74612  201600044328                  NaN     7             0            0.0   
74771  201600044419                  NaN     7             0            0.0   
74814  201600044448                  NaN     7             0            0.0   
84082  201600049181                  NaN     7             0            0.0   

       obstacle_mobile  choc  manoeuvre num_vehicule  
4153               2.0   8.0        2.0          B02  
4504               2.0   8.0        1.0          A01  
8407               2.0   2.0        9.0          A01  
12686              2.0   2.0       19.0          B02  
14845              NaN   NaN        NaN          B01  
...                ...   ...        ...          ...  
74516              2.0   3.0        1.0          A01  
74612              2.0   3.0        1.0          A01  
74771              2.0   3.0        1.0          B01  
74814              2.0   0.0        1.0          Z01  
84082              2.0   7.0       15.0          A01  

[72 rows x 9 columns]

9) Sort the data frame using the accident number column

In [55]:
df.sort_values(by=['Num_Acc']) 

Num_Acc  sens_de_Circulation  catV  nb_occupants  obstacle_fixe  \
0       201600000001                  0.0     7             0            0.0   
1       201600000001                  0.0     2             0            0.0   
2       201600000002                  0.0     7             0            6.0   
3       201600000003                  0.0     7             0            0.0   
4       201600000004                  0.0    32             0            0.0   
...              ...                  ...   ...           ...            ...   
101919  201600059430                  1.0    30             0            0.0   
101920  201600059431                  2.0    30             0            0.0   
101921  201600059431                  1.0    30             0            0.0   
101922  201600059432                  1.0     2             0            0.0   
101923  201600059432                  2.0     7             0            0.0   

        obstacle_mobile  choc  manoeuvre num_vehicule  
0                   0.0   1.0        1.0          B02  
1                   0.0   7.0       15.0          A01  
2                   0.0   1.0        1.0          A01  
3                   1.0   6.0        1.0          A01  
4                   0.0   1.0        1.0          B02  
...                 ...   ...        ...          ...  
101919              2.0   1.0       17.0          B01  
101920              2.0   7.0       15.0          A01  
101921              2.0   1.0        1.0          B01  
101922              2.0   7.0        1.0          A01  
101923              2.0   1.0        9.0          B01  

[101924 rows x 9 columns]

10) Sort the values using the accident number column, then the vehicle category column

In [56]:
df.sort_values(by=['Num_Acc','catV'])

Num_Acc  sens_de_Circulation  catV  nb_occupants  obstacle_fixe  \
1       201600000001                  0.0     2             0            0.0   
0       201600000001                  0.0     7             0            0.0   
2       201600000002                  0.0     7             0            6.0   
3       201600000003                  0.0     7             0            0.0   
5       201600000004                  0.0     7             0            0.0   
...              ...                  ...   ...           ...            ...   
101919  201600059430                  1.0    30             0            0.0   
101920  201600059431                  2.0    30             0            0.0   
101921  201600059431                  1.0    30             0            0.0   
101922  201600059432                  1.0     2             0            0.0   
101923  201600059432                  2.0     7             0            0.0   

        obstacle_mobile  choc  manoeuvre num_vehicule  
1                   0.0   7.0       15.0          A01  
0                   0.0   1.0        1.0          B02  
2                   0.0   1.0        1.0          A01  
3                   1.0   6.0        1.0          A01  
5                   0.0   8.0       15.0          A01  
...                 ...   ...        ...          ...  
101919              2.0   1.0       17.0          B01  
101920              2.0   7.0       15.0          A01  
101921              2.0   1.0        1.0          B01  
101922              2.0   7.0        1.0          A01  
101923              2.0   1.0        9.0          B01  

[101924 rows x 9 columns]

11) Select the 4153rd row. Then select row having index '4153'. What is the difference between both?

In [61]:
df.iloc[4153]
#df.loc['4153']
#not the same element but element index '4153'

Num_Acc                201600002519
sens_de_Circulation             NaN
catV                              1
nb_occupants                      0
obstacle_fixe                   0.0
obstacle_mobile                 2.0
choc                            8.0
manoeuvre                       2.0
num_vehicule                    B02
Name: 4153, dtype: object

12)  Set Num_Acc as index

a. Make sure to use `inplace=True to save the value in the dataframe

In [66]:
df.set_index('Num_Acc', inplace=True)

b. Can you still get the row having index '4153'? Explain.

No ,the row index '4153' is now '2.016e+11', but we can still obtain the 4153rst row

In [67]:
df.head(10)

sens_de_Circulation  catV  nb_occupants  obstacle_fixe  \
Num_Acc                                                                
201600000001                  0.0     7             0            0.0   
201600000001                  0.0     2             0            0.0   
201600000002                  0.0     7             0            6.0   
201600000003                  0.0     7             0            0.0   
201600000004                  0.0    32             0            0.0   
201600000004                  0.0     7             0            0.0   
201600000005                  0.0    30             0            0.0   
201600000005                  0.0     7             0            0.0   
201600000006                  0.0     7             0            0.0   
201600000007                  1.0    30             0            0.0   

              obstacle_mobile  choc  manoeuvre num_vehicule  
Num_Acc                                                      
201600000001              0.0   1.0        1.0          B02  
201600000001              0.0   7.0       15.0          A01  
201600000002              0.0   1.0        1.0          A01  
201600000003              1.0   6.0        1.0          A01  
201600000004              0.0   1.0        1.0          B02  
201600000004              0.0   8.0       15.0          A01  
201600000005              2.0   1.0       15.0          B02  
201600000005              2.0   3.0        1.0          A01  
201600000006              1.0   1.0        1.0          A01  
201600000007              0.0   3.0       15.0          A01

c. Finally, Restore the index as it was before.

In [89]:
df.reset_index(inplace=True)
df.head(10)

Num_Acc  sens_de_Circulation  catV  nb_occupants  obstacle_fixe  \
0  201600000001                  0.0     7             0            0.0   
1  201600000001                  0.0     2             0            0.0   
2  201600000002                  0.0     7             0            6.0   
3  201600000003                  0.0     7             0            0.0   
4  201600000004                  0.0    32             0            0.0   
5  201600000004                  0.0     7             0            0.0   
6  201600000005                  0.0    30             0            0.0   
7  201600000005                  0.0     7             0            0.0   
8  201600000006                  0.0     7             0            0.0   
9  201600000007                  1.0    30             0            0.0   

   obstacle_mobile  choc  manoeuvre num_vehicule  
0              0.0   1.0        1.0          B02  
1              0.0   7.0       15.0          A01  
2              0.0   1.0        1.0          A01  
3              1.0   6.0        1.0          A01  
4              0.0   1.0        1.0          B02  
5              0.0   8.0       15.0          A01  
6              2.0   1.0       15.0          B02  
7              2.0   3.0        1.0          A01  
8              1.0   1.0        1.0          A01  
9              0.0   3.0       15.0          A01

#### Exploratory Data Analysis - Queries

13) Select accident that have a vehicle number W23

In [90]:
df.loc[df['num_vehicule']=='W23']

Num_Acc  sens_de_Circulation  catV  nb_occupants  obstacle_fixe  \
4073  201600002473                  2.0     7             0            0.0   

      obstacle_mobile  choc  manoeuvre num_vehicule  
4073              0.0   0.0        1.0          W23

14) Select the top 5 accidents that caused the most damage

In [91]:

df.groupby(['Num_Acc']).sum().sort_values(by=['nb_occupants'],ascending=False).head(5)['nb_occupants']


Num_Acc
201600006084    300
201600023870    210
201600023850    200
201600023760    150
201600023740    150
Name: nb_occupants, dtype: int64

15) Count the number of damaged vehicles, by vehicle category and number of occupants

In [92]:
df2 = df.groupby(by=['catV','nb_occupants']).count()
df2

Num_Acc  sens_de_Circulation  obstacle_fixe  \
catV nb_occupants                                                
1    0                4705                 4698           4703   
2    0                3424                 3421           3422   
3    0                 436                  436            436   
7    0               64641                64585          64613   
10   0                5584                 5583           5582   
...                    ...                  ...            ...   
40   140                 1                    1              1   
     150                 2                    2              2   
     200                 1                    1              1   
     210                 1                    1              1   
99   0                 202                  202            202   

                   obstacle_mobile   choc  manoeuvre  num_vehicule  
catV nb_occupants                                                   
1    0                        4703   4704       4704          4705  
2    0                        3420   3423       3423          3424  
3    0                         436    436        436           436  
7    0                       64613  64633      64636         64641  
10   0                        5580   5583       5584          5584  
...                            ...    ...        ...           ...  
40   140                         1      1          1             1  
     150                         2      2          2             2  
     200                         1      1          1             1  
     210                         1      1          1             1  
99   0                         202    202        202           202  

[121 rows x 7 columns]

16) From the previous result, select category vehicle '40', having '140' occupants

In [93]:
df2.loc[(40,140)]

Num_Acc                1
sens_de_Circulation    1
obstacle_fixe          1
obstacle_mobile        1
choc                   1
manoeuvre              1
num_vehicule           1
Name: (40, 140), dtype: int64

17) Calculate the number of occupants by vehicle category

In [97]:
df.groupby('catV').sum()['nb_occupants']

catV
1        0
2        0
3        0
7        0
10       0
13       0
14       0
15       0
16       0
17       0
20       0
21       0
30       0
31       0
32       0
33       0
34       0
35       0
36       0
37    2743
38    1385
39     522
40    2547
99       0
Name: nb_occupants, dtype: int64

18) Compute the number of damages per vehicle category

In [98]:
df.groupby('catV').count()['Num_Acc']

catV
1      4705
2      3424
3       436
7     64641
10     5584
13      406
14     1031
15      955
16       43
17      646
20       91
21      185
30     3953
31     2360
32     2087
33     8356
34     1515
35       20
36      137
37      737
38      229
39       31
40      150
99      202
Name: Num_Acc, dtype: int64

19) Select all the lines with a category vehicle between 37 and 40 inclusive. (These values correspond to public transport)

In [102]:
df.loc[(df['catV']>=37) & (df['catV']<=40)]

Num_Acc  sens_de_Circulation  catV  nb_occupants  obstacle_fixe  \
129     201600000083                  1.0    39             0            0.0   
224     201600000148                  0.0    38             0            0.0   
278     201600000184                  0.0    37             0            1.0   
292     201600000193                  2.0    38             0            0.0   
522     201600000330                  0.0    39             1            0.0   
...              ...                  ...   ...           ...            ...   
101351  201600059075                  1.0    37             0            0.0   
101367  201600059084                  2.0    37             0            0.0   
101406  201600059103                  2.0    38             0            0.0   
101444  201600059125                  1.0    37             0            0.0   
101787  201600059339                  1.0    37             1            0.0   

        obstacle_mobile  choc  manoeuvre num_vehicule  
129                 2.0   3.0        1.0          B02  
224                 1.0   2.0        1.0          A01  
278                 1.0   5.0       16.0          A01  
292                 2.0   3.0        1.0          A01  
522                 2.0   1.0        1.0          B02  
...                 ...   ...        ...          ...  
101351              2.0   3.0        1.0          D01  
101367              2.0   1.0       15.0          B01  
101406              9.0   0.0        0.0          B01  
101444              1.0   0.0        4.0          A01  
101787              1.0   2.0        1.0          A01  

[1147 rows x 9 columns]

20) Create a new column with a Boolean value, showing whether the accident happened in public transport or not

In [103]:
df['transportPublic'] = (df['catV']>=37) & (df['catV']<=40)

21) Check that the new column is working well. For this, it is necessary to verify that the number of occupants in vehicles excluding public transport is equal to 0. Contrary to what we can see in the data in the other group.

In [104]:
df.loc[(df['transportPublic']==False) & (df['nb_occupants']!=0)]

Empty DataFrame
Columns: [Num_Acc, sens_de_Circulation, catV, nb_occupants, obstacle_fixe, obstacle_mobile, choc, manoeuvre, num_vehicule, transportPublic]
Index: []

22) Create a new dataframe, which contains only public transport accidents

In [105]:
df3 = df[df['transportPublic']==True]
df3

Num_Acc  sens_de_Circulation  catV  nb_occupants  obstacle_fixe  \
129     201600000083                  1.0    39             0            0.0   
224     201600000148                  0.0    38             0            0.0   
278     201600000184                  0.0    37             0            1.0   
292     201600000193                  2.0    38             0            0.0   
522     201600000330                  0.0    39             1            0.0   
...              ...                  ...   ...           ...            ...   
101351  201600059075                  1.0    37             0            0.0   
101367  201600059084                  2.0    37             0            0.0   
101406  201600059103                  2.0    38             0            0.0   
101444  201600059125                  1.0    37             0            0.0   
101787  201600059339                  1.0    37             1            0.0   

        obstacle_mobile  choc  manoeuvre num_vehicule  transportPublic  
129                 2.0   3.0        1.0          B02             True  
224                 1.0   2.0        1.0          A01             True  
278                 1.0   5.0       16.0          A01             True  
292                 2.0   3.0        1.0          A01             True  
522                 2.0   1.0        1.0          B02             True  
...                 ...   ...        ...          ...              ...  
101351              2.0   3.0        1.0          D01             True  
101367              2.0   1.0       15.0          B01             True  
101406              9.0   0.0        0.0          B01             True  
101444              1.0   0.0        4.0          A01             True  
101787              1.0   2.0        1.0          A01             True  

[1147 rows x 10 columns]

23) Obtain the average number of occupants by vehicle category, and sort the result

In [106]:
df.groupby('catV').mean()['nb_occupants'].sort_values()

catV
1      0.000000
36     0.000000
35     0.000000
34     0.000000
33     0.000000
32     0.000000
31     0.000000
30     0.000000
20     0.000000
21     0.000000
16     0.000000
15     0.000000
14     0.000000
13     0.000000
10     0.000000
7      0.000000
3      0.000000
2      0.000000
17     0.000000
99     0.000000
37     3.721845
38     6.048035
39    16.838710
40    16.980000
Name: nb_occupants, dtype: float64

24) Map the vehicle category, obstacles (fixed and mobile) using the dictionary defined in mapping.py (you can use the mapping.py file, but you can also create your own mappings).

In [111]:
from mapping import *

In [113]:
df.replace({"catV": info_vehicules})
df.replace({"obstancel_fixe": obstacle_fixe_labels})
df.replace({"obstacle_mobile": obstacle_labels})

Num_Acc  sens_de_Circulation  catV  nb_occupants  obstacle_fixe  \
0       201600000001                  0.0     7             0            0.0   
1       201600000001                  0.0     2             0            0.0   
2       201600000002                  0.0     7             0            6.0   
3       201600000003                  0.0     7             0            0.0   
4       201600000004                  0.0    32             0            0.0   
...              ...                  ...   ...           ...            ...   
101919  201600059430                  1.0    30             0            0.0   
101920  201600059431                  2.0    30             0            0.0   
101921  201600059431                  1.0    30             0            0.0   
101922  201600059432                  1.0     2             0            0.0   
101923  201600059432                  2.0     7             0            0.0   

       obstacle_mobile  choc  manoeuvre num_vehicule  transportPublic  
0            inconnu_0   1.0        1.0          B02            False  
1            inconnu_0   7.0       15.0          A01            False  
2            inconnu_0   1.0        1.0          A01            False  
3              Piéton   6.0        1.0          A01            False  
4            inconnu_0   1.0        1.0          B02            False  
...                ...   ...        ...          ...              ...  
101919       Véhicule   1.0       17.0          B01            False  
101920       Véhicule   7.0       15.0          A01            False  
101921       Véhicule   1.0        1.0          B01            False  
101922       Véhicule   7.0        1.0          A01            False  
101923       Véhicule   1.0        9.0          B01            False  

[101924 rows x 10 columns]

#### Heat Map - Vehicle Category vs Accident Moving Obstacle

25) Create a new database, projecting the category of the vehicle in relation to the moving obstacle. 

The values of the data frame will be the sum of the respective occupant numbers. 

This database can be referred to as a heat map of the number of accidents by type of transport and obstacle.

In [136]:
dt = pd.pivot_table(df,index='catV',columns='obstacle_mobile',values='nb_occupants',aggfunc='sum')
dt

obstacle_mobile    0.0    1.0     2.0  4.0  5.0  6.0    9.0
catV                                                       
1                  0.0    0.0     0.0  0.0  0.0  0.0    0.0
2                  0.0    0.0     0.0  0.0  0.0  0.0    0.0
3                  0.0    0.0     0.0  NaN  NaN  NaN    0.0
7                  0.0    0.0     0.0  0.0  0.0  0.0    0.0
10                 0.0    0.0     0.0  0.0  0.0  0.0    0.0
13                 0.0    0.0     0.0  0.0  NaN  NaN    0.0
14                 0.0    0.0     0.0  0.0  NaN  NaN    0.0
15                 0.0    0.0     0.0  0.0  NaN  NaN    0.0
16                 0.0    0.0     0.0  NaN  NaN  NaN    0.0
17                 0.0    0.0     0.0  0.0  0.0  0.0    0.0
20                 0.0    0.0     0.0  NaN  NaN  NaN    NaN
21                 0.0    0.0     0.0  NaN  NaN  NaN    0.0
30                 0.0    0.0     0.0  0.0  0.0  0.0    0.0
31                 0.0    0.0     0.0  0.0  0.0  0.0    0.0
32                 0.0    0.0     0.0  NaN  0.0  NaN    0.0
33                 0.0    0.0     0.0  0.0  0.0  0.0    0.0
34                 0.0    0.0     0.0  NaN  NaN  0.0    0.0
35                 0.0    NaN     0.0  NaN  NaN  NaN    NaN
36                 0.0    0.0     0.0  NaN  NaN  NaN    0.0
37               520.0  784.0  1313.0  NaN  NaN  NaN  126.0
38               256.0  210.0   917.0  NaN  NaN  NaN    2.0
39               300.0   34.0   187.0  1.0  NaN  NaN    NaN
40               171.0  883.0  1483.0  0.0  NaN  NaN   10.0
99                 0.0    0.0     0.0  NaN  NaN  NaN    0.0

26) Using the previous results, obtain the most dangerous mode of transport for the public.

In [122]:
df.groupby(by='catV').sum()['nb_occupants'].sort_values(ascending = False).index[0]

37

In [124]:
dt.sum(axis=1).sort_values(ascending = False).index[0]

37

27) Sort the heatmap from the most dangerous to the least dangerous means of transport.

In [137]:
dt['Somme'] = dt.sum(axis=1)
dt.sort_values(by='Somme', ascending = False, inplace=True)
dt

obstacle_mobile    0.0    1.0     2.0  4.0  5.0  6.0    9.0   Somme
catV                                                               
37               520.0  784.0  1313.0  NaN  NaN  NaN  126.0  2743.0
40               171.0  883.0  1483.0  0.0  NaN  NaN   10.0  2547.0
38               256.0  210.0   917.0  NaN  NaN  NaN    2.0  1385.0
39               300.0   34.0   187.0  1.0  NaN  NaN    NaN   522.0
1                  0.0    0.0     0.0  0.0  0.0  0.0    0.0     0.0
2                  0.0    0.0     0.0  0.0  0.0  0.0    0.0     0.0
36                 0.0    0.0     0.0  NaN  NaN  NaN    0.0     0.0
35                 0.0    NaN     0.0  NaN  NaN  NaN    NaN     0.0
34                 0.0    0.0     0.0  NaN  NaN  0.0    0.0     0.0
33                 0.0    0.0     0.0  0.0  0.0  0.0    0.0     0.0
32                 0.0    0.0     0.0  NaN  0.0  NaN    0.0     0.0
31                 0.0    0.0     0.0  0.0  0.0  0.0    0.0     0.0
30                 0.0    0.0     0.0  0.0  0.0  0.0    0.0     0.0
21                 0.0    0.0     0.0  NaN  NaN  NaN    0.0     0.0
20                 0.0    0.0     0.0  NaN  NaN  NaN    NaN     0.0
17                 0.0    0.0     0.0  0.0  0.0  0.0    0.0     0.0
16                 0.0    0.0     0.0  NaN  NaN  NaN    0.0     0.0
15                 0.0    0.0     0.0  0.0  NaN  NaN    0.0     0.0
14                 0.0    0.0     0.0  0.0  NaN  NaN    0.0     0.0
13                 0.0    0.0     0.0  0.0  NaN  NaN    0.0     0.0
10                 0.0    0.0     0.0  0.0  0.0  0.0    0.0     0.0
7                  0.0    0.0     0.0  0.0  0.0  0.0    0.0     0.0
3                  0.0    0.0     0.0  NaN  NaN  NaN    0.0     0.0
99                 0.0    0.0     0.0  NaN  NaN  NaN    0.0     0.0

28) Get the most dangerous moving obstacle when using public tranpsortation.

In [143]:
dt.loc[:, dt.columns != 'Somme'].sum(axis=0).sort_values(ascending = False).index[0]

2.0

29) Sort the heat map from the most dangerous to the least dangerous entity (means of transport, and moving obstacle)

In [146]:
dt.loc['Somme'] = dt.sum()
dt.sort_values(by='Somme', axis=1,ascending = False, inplace=True)
dt

obstacle_mobile   Somme     2.0     1.0     0.0    9.0  4.0  5.0  6.0
catV                                                                 
37               2743.0  1313.0   784.0   520.0  126.0  NaN  NaN  NaN
40               2547.0  1483.0   883.0   171.0   10.0  0.0  NaN  NaN
38               1385.0   917.0   210.0   256.0    2.0  NaN  NaN  NaN
39                522.0   187.0    34.0   300.0    NaN  1.0  NaN  NaN
1                   0.0     0.0     0.0     0.0    0.0  0.0  0.0  0.0
2                   0.0     0.0     0.0     0.0    0.0  0.0  0.0  0.0
36                  0.0     0.0     0.0     0.0    0.0  NaN  NaN  NaN
35                  0.0     0.0     NaN     0.0    NaN  NaN  NaN  NaN
34                  0.0     0.0     0.0     0.0    0.0  NaN  NaN  0.0
33                  0.0     0.0     0.0     0.0    0.0  0.0  0.0  0.0
32                  0.0     0.0     0.0     0.0    0.0  NaN  0.0  NaN
31                  0.0     0.0     0.0     0.0    0.0  0.0  0.0  0.0
30                  0.0     0.0     0.0     0.0    0.0  0.0  0.0  0.0
21                  0.0     0.0     0.0     0.0    0.0  NaN  NaN  NaN
20                  0.0     0.0     0.0     0.0    NaN  NaN  NaN  NaN
17                  0.0     0.0     0.0     0.0    0.0  0.0  0.0  0.0
16                  0.0     0.0     0.0     0.0    0.0  NaN  NaN  NaN
15                  0.0     0.0     0.0     0.0    0.0  0.0  NaN  NaN
14                  0.0     0.0     0.0     0.0    0.0  0.0  NaN  NaN
13                  0.0     0.0     0.0     0.0    0.0  0.0  NaN  NaN
10                  0.0     0.0     0.0     0.0    0.0  0.0  0.0  0.0
7                   0.0     0.0     0.0     0.0    0.0  0.0  0.0  0.0
3                   0.0     0.0     0.0     0.0    0.0  NaN  NaN  NaN
99                  0.0     0.0     0.0     0.0    0.0  NaN  NaN  NaN
Somme            7197.0  3900.0  1911.0  1247.0  138.0  1.0  0.0  0.0